on: 
  push:
    branches:
      - master

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.proctorglobal.ca
        username: dev_cicd1245@proctorglobal.ca
        password: Hooramshah12324@
        server-dir: /public_html/dev.dev.proctorglobal.ca/dev_cicd1245/
